### PR TITLE
Improved portability and added musl-fts

### PR DESCRIPTION
**Pull request by absolutelynothinghere**
Made changes that were discussed here: https://github.com/arp242/bsdgrep/issues/1

### CODE REVIEW

**Comment by arp242** [comment]
It generates a warning with GNU libc:

	% make clean all
	rm -f grep
	cc -std=c99 -pedantic -Wall -O2  -D_GNU_SOURCE=1 -o grep *.c
	fts.c:54:9: warning: 'MAX' macro redefined [-Wmacro-redefined]
	#define MAX(a,b) ((a)>(b)?(a):(b))
			^
	/usr/include/sys/param.h:103:9: note: previous definition is here
	#define MAX(a,b) (((a)>(b))?(a):(b))
			^
	1 warning generated.

Changing that `!defined(HAVE_DECL_MAX) || (HAVE_DECL_MAX==0)` to `defined(HAVE_MAX)` should probably fix it?

Also got some trailing whitespace in the Makefile.

**Comment by absolutelynothinghere** [comment]
The warning is now removed and the Makefile cleaned, try compiling again.

**Comment by arp242** [comment]
I just updated from upstream; I don't believe it should break any of your changes, but I didn't test it. If it does, then the modifications really should be in freebsd.h or update.sh, rather than modifying the files "directly"; this way stuff doesn't need to be manually applied on every update.

**Comment by absolutelynothinghere** [comment]
The updated code compiles cleanly and the program seems to run fine after a few quick tests, this is a great milestone!  
Please [make a new release](https://github.com/arp242/bsdgrep/releases/new) (e.g. 20231020) for this version if you can.

**Comment by arp242** [comment]
I added some (but not yet all) tests from the FreeBSD repo, and GitHub actions with musl libc, and it doesn't actually seem to work well with musl:

```
% CC=musl-gcc make check
=== test-binary_body                 FAIL
        --- /proc/self/fd/12    2023-10-20 23:32:29.695916412 +0100
        +++ /home/martin/code/Archive/bsdgrep/testdata/d_binary.out     2023-10-20 21:11:54.388412799 +0100
        @@ -1 +1 @@
        -
        +Binary file test.file matches
=== test-recurse_symlink_body        FAIL
        --- /proc/self/fd/12    2023-10-20 23:32:29.790916405 +0100
        +++ /home/martin/code/Archive/bsdgrep/testdata/d_recurse_symlink.out    2023-10-20 22:11:11.321312779 +0100
        @@ -1,2 +1,2 @@
        -test/c/match:Test string
         grep: warning: test/c/d/d: recursive directory loop
        +test/c/match:Test string
```

And then after that it seems to hang indefinitely on `test-word_regexps_body`:

```
# Checks word-regexps
test-word_regexps_body() {
	have=$($grep -w separated $testdata/d_input 2>&1)
	diff -u <(print $have) $testdata/d_word_regexps.out || return 1

	printf "xmatch pmatch\n" > test1
	have=$($grep -Eow "(match )?pmatch" test1)

	diff -u <(print $have) <(print 'pmatch') || return 1
}
```

It hangs on that first command:

```
% ./grep -w separated testdata/d_input
dot.separated@words
```

**Comment by arp242** [comment]
The problem is that `int eflags = 4 /*REG_STARTEND*/;` you did; FreeBSD libc and GNU libc has that, but musl doesn't. This means the return values for regexec() are wrong, and it all fails.

**Comment by absolutelynothinghere** [comment]
Hmm... Yes it indeed compiles fine with glibc. I was going to suggest `#define REG_STARTEND 4` but I see [this idea is already rejected](https://github.com/arp242/bsdgrep/commit/7d14cfcf5acab4e69f4c6b1dff390a6a1f7a4dfc).

Should this be [reported to musl](https://wiki.musl-libc.org/reporting-bugs) so they add `REG_STARTEND`? Or is there a way to patch the tests just like the source files?

**Comment by arp242** [comment]
> Should this be reported to musl so they add REG_STARTEND? Or is there a way to patch the tests just like the source files?

Based on [this thread](https://public-inbox.org/git/20161004150848.GA7949@brightrain.aerifal.cx/#t) I don't think it's likely that it will be added (Rich being the author of musl).

And these are real bugs, so "patch the test files" is obviously not a solution. Linking against pcre2-posix is probably the best bet; it works locally but the CI fails for some reason: #3 – also there are still two tests that fail with it, but nothing as dramatic as "will print output forever".

**Comment by absolutelynothinghere** [comment]
I'm not familiar with pcre2-posix but judging from [this repository](https://github.com/PCRE2Project/pcre2) there should be no issue using it here. It doesn't seem to have any dependencies and the [license](https://github.com/PCRE2Project/pcre2/blob/master/LICENCE) is compatible. Shame it needs CMake though...

> the CI fails for some reason

I see `test-pcre` is failing with a link error, maybe there's a linker flag missing? As per [the documentation](https://pcre2project.github.io/pcre2/doc/html/pcre2-config.html), you could use the output of `pcre2-config --libs-posix` instead of linking with `-lpcre2-posix` directly.

**Comment by arp242** [comment]
Turns out pcre2 doesn't actually implement POSIX regexps, it just provides interfaces which behave different: http://www.pcre.org/current/doc/html/pcre2posix.html#SEC3

All of this got too complex for my liking anyway. Complain to Rich for not implementing simple POSIX extensions that almost everyone else implements (BSD, GNU, Solaris, uClibc, etc.)

**Comment by arp242** [comment]
Also this includes grep with some patches to make it work on musl; you may be better off using that: https://github.com/chimera-linux/chimerautils

**Comment by absolutelynothinghere** [comment]
Sorry to hear, thank you for your efforts.

Honestly bsdgrep is good enough for my needs as it is now, even with the failing tests. Chimera grep doesn't compile because it doesn't bundle musl-fts and still depends on `<sys/cdefs.h>` and friends.

**Comment by arp242** [comment]
Okay, whatever works for you – but for some patterns it will do an infinite loop using 100% CPU, so... 😅

Personally I'd recommend taking their grep.c though and using that,  but it's your computer!

**Pull request merged**
